package smbedit

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"text/template"
	"time"
)

// The header line intentionally still says "smbed": FR-3's primary clause is
// byte-identical rendering, and the coordinated rename (template + golden
// tests together) is an explicit follow-up, not part of this port.
const confTemplate = `# Generated by smbed — do not edit by hand.
[global]
{{- range .Globals}}
   {{.Key}} = {{.Value}}
{{- end}}
{{range .Shares}}{{if .Enabled}}

[{{.Name}}]
   path = {{.Path}}
{{- if .Comment}}
   comment = {{.Comment}}
{{- end}}
   valid users = {{$.ShareOwner}}
   force user = {{$.ShareOwner}}
   read only = {{if .Writable}}no{{else}}yes{{end}}
   browseable = {{if .BrowseAble}}yes{{else}}no{{end}}
   guest ok = {{if .Public}}yes{{else}}no{{end}}
{{- end}}{{end}}
`

var confTmpl = template.Must(template.New("smb.conf").Parse(confTemplate))

// logFunc receives a line of text for every OS-level operation the module
// performs (sudo writes, backups, service restarts) so callers can surface a
// live operations log. Unlike smbed's package-global samba.Logf, the hook is
// passed per call and wired per server at construction (D-7).
type logFunc func(format string, args ...any)

// noplog is the no-op logFunc used where no operations log is wired.
func noplog(string, ...any) {}

// renderData is the data model passed to the template.
type renderData struct {
	Globals    []GlobalEntry
	Shares     []Share
	ShareOwner string
}

// Render returns the rendered smb.conf content.
func Render(st *State) ([]byte, error) {
	data := renderData{
		Globals:    st.Globals,
		Shares:     st.Shares,
		ShareOwner: st.ShareOwner,
	}
	var buf bytes.Buffer
	if err := confTmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("rendering smb.conf template: %w", err)
	}
	return buf.Bytes(), nil
}

// WriteConf renders and writes smb.conf to st.SmbConfPath, first backing up
// any existing file at that path with a timestamped suffix.
func WriteConf(st *State, logf logFunc) error {
	rendered, err := Render(st)
	if err != nil {
		return err
	}
	if err := backupExisting(st.SmbConfPath, logf); err != nil {
		return err
	}
	return writeFile(st.SmbConfPath, rendered, logf)
}

// backupExisting copies path to "<path>.<YYYYMMDD-HHMMSS>.bak" if it exists,
// preserving the prior smb.conf before it gets overwritten. It is a no-op if
// path does not exist yet.
func backupExisting(path string, logf logFunc) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("reading %s for backup: %w", path, err)
	}
	backupPath := fmt.Sprintf("%s.%s.bak", path, time.Now().Format("20060102-150405"))
	if err := writeFile(backupPath, data, logf); err != nil {
		return err
	}
	logf("backed up %s -> %s", path, backupPath)
	return nil
}

// writeFile writes data to path, falling back to a sudo-elevated copy when
// the destination isn't directly writable by the server process — smb.conf
// and its directory are typically root-owned on a real Samba install.
func writeFile(path string, data []byte, logf logFunc) error {
	err := os.WriteFile(path, data, 0o644)
	if err == nil {
		return nil
	}
	if !os.IsPermission(err) {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return writeFileWithSudo(path, data, logf)
}

// writeFileWithSudo stages data in a temp file the current user owns, then
// uses "sudo install" to place it at path with the right mode. This lets
// the module run unprivileged while still being able to update root-owned
// files, as long as the invoking user has passwordless sudo for this.
func writeFileWithSudo(path string, data []byte, logf logFunc) error {
	tmp, err := os.CreateTemp("", "smbedit-*")
	if err != nil {
		return fmt.Errorf("creating temp file for %s: %w", path, err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("writing temp file for %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("closing temp file for %s: %w", path, err)
	}

	logf("running: sudo install -m 0644 <tmp> %s", path)
	if out, err := runCommand("sudo", "install", "-m", "0644", tmpPath, path); err != nil {
		logf("ERROR: writing %s via sudo failed: %s", path, strings.TrimSpace(out+" "+err.Error()))
		return fmt.Errorf("writing %s via sudo: %w: %s", path, err, strings.TrimSpace(out))
	}
	logf("wrote %s via sudo", path)
	return nil
}

// ParseConf parses raw smb.conf content into an ordered list of [global]
// key/value pairs and a Share per non-global section. Share-level keys are
// matched case-insensitively with whitespace collapsed (e.g. "Read Only" and
// "read  only" are equivalent); unrecognized keys are ignored. shareOwner is
// a best-effort guess taken from the first "valid users" or "force user"
// line found, since a single owner is applied to all shares.
func ParseConf(data []byte) (globals []GlobalEntry, shares []Share, shareOwner string) {
	lines := joinContinuations(strings.Split(string(data), "\n"))

	var section string
	var current *Share

	flush := func() {
		if current != nil {
			shares = append(shares, *current)
			current = nil
		}
	}

	for _, raw := range lines {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			flush()
			section = strings.TrimSpace(line[1 : len(line)-1])
			if !strings.EqualFold(section, "global") {
				current = &Share{
					Name:       section,
					BrowseAble: true,
					Enabled:    true,
				}
			}
			continue
		}

		eq := strings.Index(line, "=")
		if eq < 0 {
			continue
		}
		key := normalizeKey(line[:eq])
		value := strings.TrimSpace(line[eq+1:])

		if strings.EqualFold(section, "global") {
			globals = append(globals, GlobalEntry{Key: key, Value: value})
			continue
		}
		if current == nil {
			continue
		}
		switch key {
		case "path", "directory":
			current.Path = value
		case "comment":
			current.Comment = value
		case "valid users", "force user":
			if shareOwner == "" {
				shareOwner = value
			}
		case "read only":
			current.Writable = !isYes(value)
		case "writable", "writeable":
			current.Writable = isYes(value)
		case "browseable", "browsable":
			current.BrowseAble = isYes(value)
		case "guest ok", "public":
			current.Public = isYes(value)
		}
	}
	flush()

	return globals, shares, shareOwner
}

// ReadConf reads and parses the smb.conf file at path.
func ReadConf(path string) (globals []GlobalEntry, shares []Share, shareOwner string, err error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, "", fmt.Errorf("reading %s: %w", path, err)
	}
	globals, shares, shareOwner = ParseConf(data)
	return globals, shares, shareOwner, nil
}

// joinContinuations merges lines ending in a trailing "\" with the line that
// follows, per smb.conf's line-continuation syntax.
func joinContinuations(lines []string) []string {
	var out []string
	var buf strings.Builder
	for _, l := range lines {
		trimmed := strings.TrimRight(l, "\r\n \t")
		if strings.HasSuffix(trimmed, "\\") {
			buf.WriteString(strings.TrimSuffix(trimmed, "\\"))
			buf.WriteString(" ")
			continue
		}
		buf.WriteString(trimmed)
		out = append(out, buf.String())
		buf.Reset()
	}
	if buf.Len() > 0 {
		out = append(out, buf.String())
	}
	return out
}

func normalizeKey(s string) string {
	return strings.Join(strings.Fields(strings.ToLower(s)), " ")
}

func isYes(s string) bool {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "yes", "true", "1":
		return true
	default:
		return false
	}
}

// RestartResult captures the outcome of a service restart attempt.
type RestartResult struct {
	Success bool   `json:"success"`
	Output  string `json:"output"`
}

// Restart attempts to restart the Samba service using systemctl, via sudo
// since managing systemd units is a privileged operation. It tries "smbd"
// and falls back to "smb" for distros that use that unit name.
func Restart(logf logFunc) RestartResult {
	for _, unit := range []string{"smbd", "smb"} {
		logf("running: sudo systemctl restart %s", unit)
		out, err := runCommand("sudo", "systemctl", "restart", unit)
		if err == nil {
			logf("Samba restarted successfully (unit=%s)", unit)
			return RestartResult{Success: true, Output: strings.TrimSpace(out)}
		}
		logf("systemctl restart %s failed: %s", unit, strings.TrimSpace(out+" "+err.Error()))
	}
	// Last resort: try service command.
	logf("running: sudo service smbd restart")
	out, err := runCommand("sudo", "service", "smbd", "restart")
	if err != nil {
		logf("ERROR: Samba restart failed: %s", strings.TrimSpace(out+" "+err.Error()))
		return RestartResult{Success: false, Output: strings.TrimSpace(out + " " + err.Error())}
	}
	logf("Samba restarted successfully (service smbd)")
	return RestartResult{Success: true, Output: strings.TrimSpace(out)}
}

// runCommand is a thin wrapper so tests can swap it out.
var runCommand = func(name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	out, err := cmd.CombinedOutput()
	return string(out), err
}
