package haproxy

import (
	"fmt"
	"strconv"
	"strings"
)

// ImportReport lists what Import could not map into the model, so nothing is
// lost silently.
type ImportReport struct {
	// RawKept are headers of sections preserved verbatim as raw sections.
	RawKept []string `json:"rawKept"`
	// LegacyCrtArgs are per-bind `crt` paths; certs now come via the crt-list.
	LegacyCrtArgs []string `json:"legacyCrtArgs"`
	// Unmapped are individual lines inside modelled sections that were dropped
	// or are regenerated by the renderer.
	Unmapped []string `json:"unmapped"`
}

type cfgSection struct {
	header string
	kind   string
	name   string
	lines  []string
}

var sectionKinds = map[string]bool{
	"global": true, "defaults": true, "frontend": true, "backend": true,
	"listen": true, "userlist": true, "peers": true, "resolvers": true,
	"cache": true, "program": true, "mailers": true, "http-errors": true,
}

func splitSections(data []byte) []*cfgSection {
	var out []*cfgSection
	var cur *cfgSection
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(strings.TrimRight(raw, "\r"))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		f := strings.Fields(line)
		if raw[0] != ' ' && raw[0] != '\t' && sectionKinds[f[0]] {
			cur = &cfgSection{header: strings.Join(f, " "), kind: f[0]}
			if len(f) > 1 {
				cur.name = f[1]
			}
			out = append(out, cur)
			continue
		}
		if cur == nil {
			cur = &cfgSection{header: "global", kind: "global"}
			out = append(out, cur)
		}
		cur.lines = append(cur.lines, line)
	}
	return out
}

func splitDirective(line string) Directive {
	k, v, _ := strings.Cut(line, " ")
	return Directive{Key: k, Value: strings.TrimSpace(v)}
}

// bindPort extracts the port from a bind address such as "*:443", ":443" or
// "0.0.0.0:443".
func bindPort(addr string) (int, bool) {
	i := strings.LastIndex(addr, ":")
	if i < 0 {
		return 0, false
	}
	p, err := strconv.Atoi(addr[i+1:])
	return p, err == nil && validPort(p)
}

type parsedBackend struct {
	upstream Upstream
	check    bool
	extra    []string
}

func parseBackend(s *cfgSection) (*parsedBackend, bool) {
	b := &parsedBackend{extra: []string{}}
	seen := false
	for _, l := range s.lines {
		f := strings.Fields(l)
		if f[0] == "server" && !seen && len(f) >= 3 {
			i := strings.LastIndex(f[2], ":")
			if i < 0 {
				return nil, false
			}
			p, err := strconv.Atoi(f[2][i+1:])
			if err != nil || !validPort(p) {
				return nil, false
			}
			b.upstream = Upstream{Host: f[2][:i], Port: p}
			for _, a := range f[3:] {
				if a == "check" {
					b.check = true
				}
			}
			seen = true
			continue
		}
		if f[0] == "mode" {
			continue
		}
		b.extra = append(b.extra, l)
	}
	return b, seen
}

func baseLabel(fqdn string) string {
	l, _, _ := strings.Cut(fqdn, ".")
	return l
}

// Import parses an existing haproxy.cfg into a Model. Comments are dropped;
// anything the model does not understand is kept as a raw section and listed
// in the report.
func Import(data []byte) (*Model, *ImportReport, error) {
	m := DefaultModel()
	m.Global, m.Defaults = []Directive{}, []Directive{}
	rep := &ImportReport{RawKept: []string{}, LegacyCrtArgs: []string{}, Unmapped: []string{}}

	secs := splitSections(data)
	backends := map[string]*cfgSection{}
	for _, s := range secs {
		if s.kind == "backend" && s.name != "" {
			backends[s.name] = s
		}
	}
	used := map[string]bool{}
	nextID := 0
	haveDefault := false

	raw := func(s *cfgSection) {
		m.RawSections = append(m.RawSections, RawSection{Header: s.header, Lines: append([]string{}, s.lines...)})
		rep.RawKept = append(rep.RawKept, s.header)
	}

	var rawBackends []*cfgSection
	for _, s := range secs {
		switch s.kind {
		case "global":
			for _, l := range s.lines {
				d := splitDirective(l)
				if d.Key == "stats" && strings.HasPrefix(d.Value, "socket") {
					rep.Unmapped = append(rep.Unmapped, l)
					continue
				}
				m.Global = append(m.Global, d)
			}
		case "defaults":
			for _, l := range s.lines {
				m.Defaults = append(m.Defaults, splitDirective(l))
			}
		case "frontend":
			if !importFrontend(m, rep, s, backends, used, &nextID, &haveDefault) {
				raw(s)
			}
		case "backend":
			rawBackends = append(rawBackends, s)
		default:
			raw(s)
		}
	}
	for _, s := range rawBackends {
		if !used[s.name] {
			raw(s)
		}
	}
	return m, rep, nil
}

// importFrontend maps a TLS frontend into the model. It returns false (and
// touches nothing) when the frontend should be kept raw instead.
func importFrontend(m *Model, rep *ImportReport, s *cfgSection, backends map[string]*cfgSection, used map[string]bool, nextID *int, haveDefault *bool) bool {
	port := 0
	var crts []string
	acls := map[string][]string{}
	type rule struct{ backend, acl string }
	var rules []rule
	defBackend := ""
	var unmapped []string

	for _, l := range s.lines {
		f := strings.Fields(l)
		switch {
		case f[0] == "bind" && len(f) >= 2 && port == 0:
			p, ok := bindPort(f[1])
			ssl := false
			for _, a := range f[2:] {
				if a == "ssl" {
					ssl = true
				}
			}
			if !ok || !ssl {
				return false
			}
			port = p
			for i := 2; i < len(f); i++ {
				if f[i] == "crt" && i+1 < len(f) {
					crts = append(crts, f[i+1])
					i++
				}
			}
		case f[0] == "mode":
		case len(f) == 2 && f[0] == "option" && (f[1] == "httplog" || f[1] == "forwardfor"):
			// Emitted by the generator for every TLS frontend (fixed policy), so
			// not "unmapped" on re-import.
		case f[0] == "acl" && len(f) >= 5 && f[2] == "hdr(host)" && f[3] == "-i":
			var fq []string
			for _, h := range f[4:] {
				if i := strings.LastIndex(h, ":"); i >= 0 {
					h = h[:i]
				}
				dup := false
				for _, e := range fq {
					dup = dup || e == h
				}
				if !dup {
					fq = append(fq, h)
				}
			}
			acls[f[1]] = fq
		case f[0] == "use_backend" && len(f) == 4 && f[2] == "if" && acls[f[3]] != nil:
			rules = append(rules, rule{f[1], f[3]})
		case f[0] == "default_backend" && len(f) == 2:
			defBackend = f[1]
		default:
			unmapped = append(unmapped, l)
		}
	}
	if port == 0 {
		return false
	}
	// Every referenced backend must be a simple one-server backend.
	pbs := map[string]*parsedBackend{}
	refs := []string{defBackend}
	for _, r := range rules {
		refs = append(refs, r.backend)
	}
	for _, name := range refs {
		if name == "" {
			continue
		}
		bs := backends[name]
		if bs == nil {
			return false
		}
		pb, ok := parseBackend(bs)
		if !ok {
			return false
		}
		pbs[name] = pb
	}

	rep.LegacyCrtArgs = append(rep.LegacyCrtArgs, crts...)
	rep.Unmapped = append(rep.Unmapped, unmapped...)

	addService := func(name string, fqdns []string, pb *parsedBackend) {
		*nextID++
		cert := ""
		if len(fqdns) > 0 {
			cert = fqdns[0]
		}
		m.Services = append(m.Services, Service{
			ID: fmt.Sprintf("s%d", *nextID), Name: name, Enabled: true,
			FQDNs: fqdns, ExposedPort: port, Upstream: pb.upstream, Check: pb.check,
			Cert: CertRef{FQDN: cert}, Extra: pb.extra,
		})
	}

	for _, r := range rules {
		fq := acls[r.acl]
		name := strings.TrimSuffix(r.backend, "_backend")
		if len(fq) > 0 {
			name = baseLabel(fq[0])
		}
		used[r.backend] = true
		addService(name, append([]string{}, fq...), pbs[r.backend])
	}

	if defBackend != "" {
		used[defBackend] = true
		pb := pbs[defBackend]
		if port == 443 {
			if !*haveDefault {
				m.DefaultService = DefaultService{Name: m.DefaultService.Name, Upstream: pb.upstream, Check: pb.check}
				*haveDefault = true
			}
		} else {
			name := strings.TrimSuffix(defBackend, "_backend")
			addService(name, []string{}, pb)
			m.Ports = append(m.Ports, Port{Port: port, DefaultService: name})
		}
	} else if port != 443 {
		m.Ports = append(m.Ports, Port{Port: port})
	}
	return true
}
