#!/usr/bin/env bash
# Test rig for the haproxy editor module on a Linux host that ALREADY runs a real
# HAProxy (hero). It gives the editor a second, completely separate HAProxy to
# manage, plus a second editor instance running as a locked-down user, so that:
#   * the real HAProxy and its traffic are never touched, and
#   * the scoped sudoers from docs/guides/haproxy.md is genuinely exercised (the
#     rig user has NO other privilege, so any command the editor needs that the
#     guide's sudoers does not allow fails here, instead of passing on blanket sudo).
#
# WHY A NETWORK NAMESPACE: HAProxy sets SO_REUSEPORT on its listeners by default, so
# a second instance binding *:443 in the normal namespace would be handed a share of
# the REAL traffic by the kernel. The test HAProxy therefore runs in its own network
# namespace (own loopback, own :443, nothing shared). Test backends and test clients
# run inside it via `ip netns exec`. Filesystem paths and unix sockets are shared.
#
# Layout:
#   /etc/haproxy-test/              config, certs, crt-list, backups (the test HAProxy's files)
#   /run/haproxy-test/              the stats socket
#   haproxy-test.service            the test HAProxy (inside the namespace)
#   hp-rig                          system user that runs the second editor instance
#   /var/lib/hp-rig/                that instance's config.json and data
#   unified-haproxy-test.service    the second editor instance, http://127.0.0.1:18788
#   /etc/sudoers.d/unified-haproxy-test   generated FROM docs/guides/haproxy.md, paths substituted
#
# Usage: scripts/haproxy-test-rig.sh up | down | status | check | backends | curl <host> [path] | sudo-check
#   up          build the whole rig and start it (needs CERTMACHINE_KEY, see below)
#   down        stop and remove everything the rig created (the real HAProxy is never touched)
#   status      rig and real HAProxy side by side
#   check       prove the rig is isolated from the real HAProxy
#   backends    (re)start two tiny HTTP backends inside the namespace: 127.0.0.1:19001 and :19002
#   curl        curl a name through the TEST HAProxy:   curl rig-a.cmdhome.net /
#   sudo-check  show exactly what the rig user may run with sudo
#
# Environment for `up`:
#   CERTMACHINE_KEY=<api key>   required: the editor pulls certs from CertMachine with it
#   CERTMACHINE_URL=...         default https://certmachine.cmdhome.net
#   EDITOR_PORT=18788           port of the second editor instance
#
# Reach the rig's editor from your laptop with an SSH tunnel (no firewall change needed):
#   ssh -L 18788:127.0.0.1:18788 hero      then browse http://localhost:18788/

set -u
NS=haproxy-test
ETC=/etc/haproxy-test
RUN=/run/haproxy-test
HP_UNIT=/etc/systemd/system/haproxy-test.service
UI_UNIT=/etc/systemd/system/unified-haproxy-test.service
SUDOERS=/etc/sudoers.d/unified-haproxy-test
RIG_USER=hp-rig
RIG_HOME=/var/lib/hp-rig
EDITOR_PORT="${EDITOR_PORT:-18788}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HAPROXY=/usr/sbin/haproxy
S="sudo -n"

say()  { printf '%s\n' "$*"; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
netns_up() { $S ip netns list 2>/dev/null | grep -qw "$NS"; }
real_pid() { systemctl show -p MainPID --value haproxy 2>/dev/null; }

# The sudoers text comes from the guide itself, with the rig's paths substituted, so the
# rig tests the documentation as written.
gen_sudoers() {
  python3 - "$REPO/docs/guides/haproxy.md" "$ETC" "$RIG_USER" "$RIG_HOME" <<'PY'
import re, sys
guide, etc, user, home = sys.argv[1:5]
text = open(guide).read()
m = re.search(r"A starting point for `/etc/sudoers\.d/haproxy-editor`.*?```\n(.*?)```", text, re.S)
if not m:
    sys.exit("could not find the sudoers block in the guide")
s = m.group(1)
s = s.replace("/etc/haproxy", etc)
s = re.sub(r"(systemctl (?:reload|restart|start|is-active)) haproxy\b", r"\1 haproxy-test", s)
s = s.replace("/opt/unified-webapp/data/haproxy/staging", home + "/haproxy-data/staging")
s = re.sub(r"^cdelezenski ALL", user + " ALL", s, flags=re.M)
print("# GENERATED by scripts/haproxy-test-rig.sh from docs/guides/haproxy.md. Do not edit.")
print(s)
PY
}

do_up() {
  command -v ip >/dev/null && command -v systemctl >/dev/null || die "ip and systemctl are required"
  [ -x "$HAPROXY" ] || die "$HAPROXY not found"
  command -v go >/dev/null || die "go is required to build the rig's own copy of the app"
  [ -n "${CERTMACHINE_KEY:-}" ] || die "set CERTMACHINE_KEY to a CertMachine API key"
  CERTMACHINE_URL="${CERTMACHINE_URL:-https://certmachine.cmdhome.net}"
  $S true || die "passwordless sudo is required to build the rig"

  say "== 1. network namespace (isolates the test HAProxy's ports from the real one)"
  netns_up || $S ip netns add "$NS" || die "cannot create the namespace"
  $S ip -n "$NS" link set lo up

  say "== 2. rig user and directories"
  id "$RIG_USER" >/dev/null 2>&1 || $S useradd --system --home-dir "$RIG_HOME" --create-home --shell /sbin/nologin "$RIG_USER" || die "useradd failed"
  $S install -d -m 0755 "$ETC"
  # NOTE: certs/ and backups/ are deliberately NOT created here: the editor must create them
  # itself on its first write (that is one of the things this rig verifies).
  $S install -d -m 0750 -o "$RIG_USER" -g "$RIG_USER" "$RIG_HOME" "$RIG_HOME/haproxy-data" "$RIG_HOME/bin"
  say "   building the rig's own copy of the app from the current source (the live service's binary is not touched)"
  local bin; bin=$(mktemp)
  (cd "$REPO" && go build -o "$bin" ./cmd/server) || { rm -f "$bin"; die "go build failed"; }
  $S install -m 0755 -o "$RIG_USER" -g "$RIG_USER" "$bin" "$RIG_HOME/bin/unified-webapp"; rm -f "$bin"
  if ! $S test -f "$ETC/haproxy.cfg"; then
    $S tee "$ETC/haproxy.cfg" >/dev/null <<'CFG'
# seed config for the haproxy editor test rig (the editor adopts and replaces it)
global
    log /dev/log local0
    maxconn 200
defaults
    mode http
    timeout connect 5s
    timeout client  30s
    timeout server  30s
frontend rig_seed
    bind 127.0.0.1:19999
    default_backend rig_seed_backend
backend rig_seed_backend
    server s 127.0.0.1:19001
CFG
  fi

  say "== 3. test HAProxy unit (runs inside the namespace)"
  $S tee "$HP_UNIT" >/dev/null <<UNITEOF
[Unit]
Description=HAProxy test rig for the haproxy editor (isolated network namespace)
After=network-online.target

[Service]
NetworkNamespacePath=/run/netns/$NS
RuntimeDirectory=haproxy-test
Environment="CONFIG=$ETC/haproxy.cfg" "PIDFILE=/run/haproxy-test.pid"
ExecStartPre=$HAPROXY -f \$CONFIG -c -q
ExecStart=$HAPROXY -Ws -f \$CONFIG -p \$PIDFILE
ExecReload=$HAPROXY -f \$CONFIG -c -q
ExecReload=/bin/kill -USR2 \$MAINPID
KillMode=mixed
SuccessExitStatus=143
Type=notify
UNITEOF

  say "== 4. scoped sudoers for $RIG_USER (generated from the guide, validated before install)"
  local tmp; tmp=$(mktemp)
  gen_sudoers > "$tmp" || { rm -f "$tmp"; die "could not generate the sudoers file"; }
  if $S visudo -cf "$tmp" >/dev/null 2>&1; then
    $S install -m 0440 -o root -g root "$tmp" "$SUDOERS"; say "   installed $SUDOERS"
  else
    $S visudo -cf "$tmp" 2>&1 | head -5; rm -f "$tmp"; die "generated sudoers did not validate: NOT installed (sudo unchanged)"
  fi
  rm -f "$tmp"

  say "== 5. start the test HAProxy"
  $S systemctl daemon-reload
  $S systemctl start haproxy-test || { $S journalctl -u haproxy-test -n 15 --no-pager; die "haproxy-test failed to start"; }
  say "   haproxy-test: $(systemctl is-active haproxy-test)"
  do_backends

  say "== 6. second editor instance as $RIG_USER on 127.0.0.1:$EDITOR_PORT (config for the TEST HAProxy only)"
  local cfg="$RIG_HOME/config.json" base; base=$(mktemp)
  "$RIG_HOME/bin/unified-webapp" -init-config -config "$base" >/dev/null 2>&1 || die "could not create a base config"
  python3 - "$base" "$cfg.new" "$EDITOR_PORT" "$REPO" "$ETC" "$RUN" "$RIG_HOME" "$CERTMACHINE_URL" <<'PY' || die "config generation failed"
import json, os, sys
base, out, port, repo, etc, run, home, cm_url = sys.argv[1:9]
key = os.environ["CERTMACHINE_KEY"]
c = json.load(open(base))
for k in list(c):
    if k in ("grocery","todo","slideshow","menuserver","obsidianoid","multissh","smbedit","issuetracker",
             "timetracker","sampler","admin","taskmaster","certmachine","utuber"):
        c.pop(k, None)
c["port"] = int(port)
c["host_routing"] = {"localhost": "haproxy", "127.0.0.1": "haproxy"}
c["auth"] = {}
c.setdefault("server", {})["shared_static_dir"] = repo + "/web/shared"
c["haproxy"] = {
    "static_dir": repo + "/web/haproxy",
    "data_dir": home + "/haproxy-data",
    "os": "rocky",
    "config_path": etc + "/haproxy.cfg",
    "certs_dir": etc + "/certs",
    "crt_list_path": etc + "/crt-list.txt",
    "backup_dir": etc + "/backups",
    "stats_socket_path": run + "/admin.sock",
    "service_name": "haproxy-test",
    "certmachine": {"url": cm_url, "api_key": key, "ca_file": ""},
}
json.dump(c, open(out, "w"), indent=2)
PY
  $S install -m 0600 -o "$RIG_USER" -g "$RIG_USER" "$cfg.new" "$cfg" && rm -f "$cfg.new" "$base"
  $S tee "$UI_UNIT" >/dev/null <<UIEOF
[Unit]
Description=haproxy editor test rig: second unified-webapp instance (user $RIG_USER, scoped sudo only)
After=network-online.target

[Service]
User=$RIG_USER
WorkingDirectory=$REPO
ExecStart=$RIG_HOME/bin/unified-webapp -config $cfg
Restart=on-failure
RestartSec=3
UIEOF
  $S systemctl daemon-reload
  $S systemctl restart unified-haproxy-test
  sleep 2
  local code; code=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$EDITOR_PORT/api/status")
  [ "$code" = 200 ] && say "   editor instance answers (GET /api/status = 200)" || { $S journalctl -u unified-haproxy-test -n 15 --no-pager; die "editor instance did not come up (status $code)"; }
  say
  say "Rig is up. From your laptop:  ssh -L $EDITOR_PORT:127.0.0.1:$EDITOR_PORT hero   then   http://localhost:$EDITOR_PORT/"
  say "Test names through the TEST HAProxy:  $0 curl <name> /     Isolation proof:  $0 check"
}

do_backends() {
  netns_up || die "namespace not up (run: $0 up)"
  $S pkill -f "http.server 1900[12] --bind 127.0.0.1" 2>/dev/null; sleep 0.3
  for p in 19001 19002; do
    $S ip netns exec "$NS" bash -c "cd /tmp && nohup python3 -m http.server $p --bind 127.0.0.1 >/dev/null 2>&1 &"
  done
  sleep 0.8
  for p in 19001 19002; do
    $S ip netns exec "$NS" curl -s -o /dev/null -w "   backend 127.0.0.1:$p (in the namespace) -> %{http_code}\n" "http://127.0.0.1:$p/" || say "   backend :$p not answering"
  done
}

do_down() {
  say "== removing the rig (the real HAProxy is not touched: main pid $(real_pid))"
  $S systemctl stop unified-haproxy-test haproxy-test 2>/dev/null
  $S pkill -f "http.server 1900[12] --bind 127.0.0.1" 2>/dev/null
  $S rm -f "$HP_UNIT" "$UI_UNIT" "$SUDOERS"
  $S systemctl daemon-reload
  netns_up && $S ip netns delete "$NS"
  $S rm -rf "$ETC" "$RUN" /run/haproxy-test.pid
  id "$RIG_USER" >/dev/null 2>&1 && $S userdel -r "$RIG_USER" 2>/dev/null
  $S rm -rf "$RIG_HOME"
  say "   removed: units, sudoers, namespace, $ETC, $RUN, user $RIG_USER, $RIG_HOME"
}

do_status() {
  say "real HAProxy      : $(systemctl is-active haproxy), main pid $(real_pid), :443 listeners on host: $(ss -ltn 2>/dev/null | awk '$4 ~ /:443$/' | wc -l)"
  say "test HAProxy      : $(systemctl is-active haproxy-test 2>/dev/null); namespace $(netns_up && echo present || echo absent)"
  netns_up && $S ip netns exec "$NS" ss -ltn 2>/dev/null | awk 'NR>1 {print "   in-namespace listener: " $4}'
  say "rig editor        : $(systemctl is-active unified-haproxy-test 2>/dev/null) (http://127.0.0.1:$EDITOR_PORT/)"
  $S test -S "$RUN/admin.sock" && say "stats socket       : $RUN/admin.sock present" || say "stats socket       : not created yet (the editor's first Apply creates it)"
}

do_check() {
  say "== isolation check"
  netns_up || die "namespace not up"
  local fails=0 host443 ns443
  host443=$(ss -ltn 2>/dev/null | awk '$4 ~ /:443$/' | wc -l)
  ns443=$($S ip netns exec "$NS" ss -ltn 2>/dev/null | awk '$4 ~ /:443$/' | wc -l)
  [ "$host443" -ge 1 ] && say "PASS  the real :443 listener is on the host namespace" || { say "FAIL  no real :443 listener on the host"; fails=$((fails+1)); }
  if [ "$ns443" -eq 0 ]; then
    if $S ip netns exec "$NS" python3 -c "
import socket
s=socket.socket(); s.bind(('0.0.0.0',443)); print('bound')" >/dev/null 2>&1; then
      say "PASS  inside the namespace :443 is free and bindable although the host's :443 is in use: no shared port, no traffic can leak"
    else say "FAIL  could not bind :443 inside the namespace"; fails=$((fails+1)); fi
  else
    say "INFO  the rig HAProxy now listens on :443 inside its own namespace ($ns443 listener); host still has $host443 (separate)"
  fi
  say "INFO  real HAProxy main pid: $(real_pid) (compare before and after any rig action: it must never change)"
  [ "$fails" = 0 ] && say "ISOLATED" || exit 1
}

do_curl() {
  local host="${1:?usage: curl <host> [path]}" path="${2:-/}" ca="${CAFILE:-/tmp/certmachine-root.crt}"
  [ -s "$ca" ] || { curl -sk https://certmachine.cmdhome.net/api/ca/root.crt -o "$ca" || die "could not fetch the CertMachine root CA; set CAFILE="; }
  $S ip netns exec "$NS" curl -sS --max-time 10 --cacert "$ca" --resolve "$host:443:127.0.0.1" "https://$host$path" -o /dev/null \
    -w "$host -> http %{http_code}, certificate verified: %{ssl_verify_result} (0 = ok)\n"
}

do_sudo_check() {
  say "== what $RIG_USER may run with sudo (this is ALL it can do as root):"
  $S -u "$RIG_USER" sudo -n -l 2>&1 | sed 's/^/   /' | head -60
}

case "${1:-}" in
  up) do_up ;; down) do_down ;; status) do_status ;; check) do_check ;;
  backends) do_backends ;; curl) shift; do_curl "$@" ;; sudo-check) do_sudo_check ;;
  *) sed -n '2,/^set -u/p' "$0" | sed 's/^# \{0,1\}//' | head -48; exit 2 ;;
esac
